### ISSUE TITLE
How to proxy requests?

### ISSUE THREAD

**Issue by red010182** [Building42/Telegraph#127]
I'm using telegraph to serve a local html folder. However, I need to send a post request to a remote server which I can't add CORS header. 

So I need to proxy the post request. I'm trying to do this 

```swift
class ProxyHandler: HTTPRequestHandler {
    func respond(to request: HTTPRequest, nextHandler: HTTPRequest.Handler) throws -> HTTPResponse? {
        
        if request.method == .POST {
            request.uri = URI("http://my-domain.com")!
        }
        
        let response = try nextHandler(request)
        response?.headers.accessControlAllowOrigin = "*"

        return response
    }
}
```

But my client (WKWebview) got 404 response. Can anyone help?

Thanks

**Comment by yvbeek** [comment]
Hi, unfortunately it is a bit more complicated to get data from a remote server.

You basically have two options: 

**Option 1**: Send a redirect header back to the client. The client's app / browser will get the file from the remote server. The demo app includes an example of how to do this:

https://github.com/Building42/Telegraph/blob/main/Examples/Demo/TelegraphDemo.swift#L71
https://github.com/Building42/Telegraph/blob/main/Examples/Demo/TelegraphDemo.swift#L134

**Option 2**: The server could perform the request using an URLSession and then when the result is ready, send the response back to the client. Telegraph doesn't support that scenario right now, because you would have to keep the request open until the remote request is done.
