### ISSUE TITLE
How to upload file to server ?

### ISSUE THREAD

**Issue by conghieu021299** [Building42/Telegraph#128]
I have an image at "/private/var/mobile/Containers/Shared/AppGroup/5D607506-C125-4CF2-BCBB-67EF9F37B10E/image". 
I want to push it to the server so that when the user accesses the url "http://localhost/image" the image will be displayed. Is there any way to do that?

**Comment by yvbeek** [comment]
You can send the image from the client to your Telegraph server by posting it to an endpoint. This should work fine as long as you're not sending huge photos, because that will use up a lot of memory.

1. set up a server route that serves all the images in a local folder, this will be the route that your clients will call to display any of the uploaded images
2. set up a server route that you can use to post images, in the handler you will find the image data in `request.body`
3. when you receive image data, write the `request.body` to the folder that you created in step 1
4. on the client you can just read the image using the `Data` class and use a URLSession to post it to your Telegraph server

These resources might be helpful: 
- Apple: [reading data](https://developer.apple.com/documentation/foundation/data/3126626-init) and [writing data](https://developer.apple.com/documentation/foundation/data/1779858-write) 
- Telegraph: [HTTP routes](https://github.com/Building42/Telegraph#http-routes)
- Telegraph: [demo app code](https://github.com/Building42/Telegraph/blob/main/Examples/Demo/TelegraphDemo.swift)
