### ISSUE TITLE
WebSockets handshake request query string not available through params

### ISSUE THREAD

**Issue by TomasHubelbauer** [Building42/Telegraph#13]
I am using `handshake.params["test"]` but the `params` dictionary is empty. `handshake.uri.components.query` is correct: `"test=test"`. Is this intended behavior?

**Comment by Zyphrax** [comment]
QueryString parameters and POST data do not end up in the `params` dictionary. The name `params` might be a bit confusing, because at the moment only the route parameters end up in the `params` dictionary.

If you like you can create a `HTTPRequestHandler` that takes the QueryString parameters from the `HTTPRequest` and adds them to the request's `params` dictionary:

```swift
import Foundation
import Telegraph

public class HTTPRequestParamsHandler: HTTPRequestHandler {
  public func respond(to request: HTTPRequest, nextHandler: HTTPRequest.Handler) throws -> HTTPResponse? {
    // Extract the QueryString items and put them in the HTTPRequest params
    request.uri.queryItems?.forEach { item in
      request.params[item.name] = item.value
    }

    // Continue with the rest of the handlers
    return try nextHandler(request)
  }
}
```

Then add the handler to the server's handlers:
```swift
let paramsHandler = HTTPRequestParamsHandler()
server.httpConfig.requestHandlers.insert(paramsHandler, at: 0)
```

Note that this will overwrite any route parameters with the provided querystring parameters. But this gives you the flexibility to handle it to your likings.

**Comment by TomasHubelbauer** [comment]
@Zyphrax The sample handler is exactly what I'll need and it seems like a neat way to achieve it. Thanks!
