### ISSUE TITLE
IOS Test App provided does not allow connection from outside device

### ISSUE THREAD

**Issue by ZackHon12027** [Building42/Telegraph#133]
When running on Simulator it works fine, However. When running on Iphone you will get a ERROR: connect ECONNREFUSED. Error is true for both HTTP and HTTPS

TestApp on Main branch used. Not sure if It came by default but I added Allows Local Networking
<img width="575" alt="Screen Shot 2022-10-07 at 5 14 39 PM" src="https://user-images.githubusercontent.com/115322774/194653412-6d5fe3d9-f719-4be5-baab-d71e8c7cac22.png">

Here are some samples
(Simulator)
![Screen Shot 2022-10-07 at 5 12 43 PM](https://user-images.githubusercontent.com/115322774/194653182-964b5d82-411a-40ed-8826-4c0c82c2ac29.png)

(IOS-Iphone 13 Pro with OS 16.0.2)
![Screen Shot 2022-10-07 at 5 13 42 PM](https://user-images.githubusercontent.com/115322774/194653316-0ef98d50-69c5-4408-b2bf-5522d5ce75d4.png)

**Comment by yvbeek** [comment]
Hi, when you create the `Server`, please make sure that you're not binding it to interface `localhost`.

```swift
// This server will only be accessible on localhost
try! server.start(port: 9000, interface: "localhost")

// This server will be accessible from other devices
try! server.start(port: 9000)
```

Next, when you try to connect to the Telegraph server running on your phone, make sure that you connect using the IP address of your phone instead of `localhost`

I'll close this for now, let me know if you run into any issues.
