### ISSUE TITLE
Basic unsecured server not working

### ISSUE THREAD

**Issue by SmileAppDev** [Building42/Telegraph#14]
When I use the demo that comes with Telegraph the server starts and works perfectly, however when I try to just test an unsecured server it doesn't work.

The demo code that works: 
```swift
server = Server(identity: identity, caCertificates: [caCertificate])
server.webSocketConfig.pingInterval = 10
server.webSocketDelegate = self

// Define the demo routes
server.route(.get, "hello/:name", serverHandleGreeting)
server.route(.get, "hello(/)", serverHandleGreeting)
server.route(.get, "secret/*") { .forbidden }
server.route(.get, "status") { (.ok, "Server is running") }
server.serveBundle(.main, "/")
    
// Start the server on localhost, we'll skip error handling for the demo
// Note: if you test in your browser, don't forget to type https://
try! server.start(onPort: 9000)
serverLog("Server is running at https://localhost:9000")
```

My test of a basic server that doesn't work: 
```swift
let server = Server()      
server.route(.get, "status") { (.ok, "Server is running") }
        
try! server.start(onPort: 9000)
```

**Comment by TomasHubelbauer** [comment]
Did you make sure to access it on a correct IP (and port) and through HTTP not HTTPS? Also what does *does not work* mean? Does the app break or is it just that the server is not listening without any apparent error?

**Comment by SmileAppDev** [comment]
I tried to connect to it using localhost:9000. By "does not work" I mean the code runs but can't access the server from the browser. There are no errors in the console. 

When running the example code I get this: 
<img width="431" alt="screen shot 2017-08-01 at 11 00 47 am" src="https://user-images.githubusercontent.com/9518504/28837198-232122ae-76a9-11e7-81bc-097403ddcf43.png">

But when I run the basic server I get this: 
<img width="959" alt="screen shot 2017-08-01 at 11 01 47 am" src="https://user-images.githubusercontent.com/9518504/28837220-2e873aac-76a9-11e7-9696-8cbc137a7890.png">

**Comment by TomasHubelbauer** [comment]
You are using HTTPS in your second picture. You said you are configuring unsecure server - as your example code suggests as well. Does it work with `http://`?

**Comment by SmileAppDev** [comment]
No, I tried that as well, I just didn't catch it for the picture. 

http:// gets the same thing.
<img width="666" alt="screen shot 2017-08-01 at 11 07 26 am" src="https://user-images.githubusercontent.com/9518504/28837376-c710ee3a-76a9-11e7-9f83-d4c534248c4f.png">

**Comment by TomasHubelbauer** [comment]
I see. I don't have experience with using localhost, what I did was include the embedded (unsecured) server in an app and then connect to the phone's local network IP from a browser on a laptop (both the Mac I deployed the app from and a different one). What steps are you doing here to be able to use `localhost`? I am asking so I can try and reproduce this myself to try to help further if possible.

**Comment by TomasHubelbauer** [comment]
Oh I just realized you are probably using a macOS app instead of an iOS app right?

**Comment by SmileAppDev** [comment]
Ya I am,  I was just going to test if it works on IOS.

**Comment by SmileAppDev** [comment]
It didn't work on IOS either.

**Comment by TomasHubelbauer** [comment]
@SmileAppDev I am able to reproduce this issue. Can't assist you further sadly, but hopefully @Zyphrax will be. Interestingly, port 80 works for me on iOS no problem, but on macOS it throws "bad instruction"

**Comment by TomasHubelbauer** [comment]
@SmileAppDev Ah, that is interesting. Let me upload an example for you to check out and try, I got this working on iOS no problem.

**Comment by SmileAppDev** [comment]
Ok, Thanks for the help!

**Comment by Zyphrax** [comment]
Port 80 and 443 are in the range of the protected port numbers. Unfortunately you are very likely to have issues when you use there port numbers. They require administrative privileges, which should be possible on macOS but not on the other platforms. See: [why can't I use port 80 and 443](https://github.com/Building42/Telegraph#why-cant-i-use-port-80-and-443).

A few minutes ago I've tested the unsecured server by:
- commenting out lines 23 and 24 in `TelegraphDemo.swift`, to disable the demo routine, they will all fail because they assume https.
- changed line 43 in that file to: `server = Server()`

Then I start up the macOS app and a fresh Chrome window and visit `http://localhost:9000/status`. That seems to work:

![image](https://user-images.githubusercontent.com/966500/28880909-6fbb60b8-7774-11e7-8d4d-2b072e8eeb37.png)

The root test site works as well:
![image](https://user-images.githubusercontent.com/966500/28880941-8558af20-7774-11e7-8fe9-c0765ecbd117.png)

Chrome is really eager to change your url to `https` if you've visited the site with `http` before. I'll try out the iOS version in a few minutes.

**Comment by TomasHubelbauer** [comment]
@SmileAppDev Sorry I did not have time to get back to you, hopefully Yvo's suggestion to "downgrade" the secure demo will work for you
@Zyphrax I was able to use port 80 on iOS without any extra permissions or privileges - should I expect problems when going to the store with the app as opposed to in development (while deploying from the Mac to developer iPhone)?

**Comment by Zyphrax** [comment]
Interesting, I believe the simulator doesn't allow it, but it might be allowed on the actual device. See the comment by Kalle on [this Stack Overflow post](https://stackoverflow.com/a/3326000/136819). I'm not sure if Apple will break that in the future, but for now it might work.

I've just tested the iOS version and it runs without any issues.

@SmileAppDev if you have an example app, I'd be happy to have a look at the problem.

One last thing I can think off. Are you retaining the `Server` instance? If you aren't retaining it, the `Server` instance will be deallocated and automatically stopped.

**Comment by Zyphrax** [comment]
Interesting, it seems to be allowed on the actual device but not on the Simulator. See [this StackOverflow post](https://stackoverflow.com/questions/3325785/web-server-on-port-80-on-iphone/3326000). I'm not really sure, I'd have to do some tests with this.

The unsecure server is working for me on iOS, without any problems.

@SmileAppDev are you retaining the `Server` instance? In `TelegraphDemo` I'm assigning the `Server` instance to a local variable so that it doesn't get deallocated then the `setupServer` function goes out of scope. If the `Server` instance gets deallocated, it will automatically stop and close the sockets.

**Comment by SmileAppDev** [comment]
Thank you @Zyphrax the server was getting deallocated.

**Comment by Zyphrax** [comment]
@SmileAppDev Ah yes, that's an easy mistake to make. I'm glad this isn't a bug :)
Thanks for letting me know.

**Comment by hrbrmstr** [comment]
Just a nod to @yvbeek for the "deallocation" hint. I'm also working on an app that serves out of `localhost` on *OS and ended up starting it in the main `ContentView` of the SwiftUI app. Likely saved me hours or days of frustration.
