### ISSUE TITLE
iOS8 support?

### ISSUE THREAD

**Issue by Joe0708** [Building42/Telegraph#16]
My app should support iOS8, , but Telegraph did not support ios8.0. i should how to do?

**Comment by Daij-Djan** [comment]
don’t use telegram or (better imo) don’t care about ios8 anymore

**Comment by Zyphrax** [comment]
@Joe0708 With Telegraph I've targeted iOS 9 because of ATS (Application Transport Security), but I might be able to lower the requirements.

Somewhere next week I'm going to make changes to the library for Swift 4, I'll have a look at the minimal requirements as well.

@Daij-Djan Everybody should use Telegraph 😄

**Comment by Zyphrax** [comment]
I've added iOS 8 support with commit https://github.com/Building42/Telegraph/commit/21b37912071de635c45a77f5ac22d3ba014deaca.

I ran into some headache with the regular expressions for route handling. I was relying on named groups and that wasn't available in iOS 8. I've added a workaround, but please test things well and let me know if you encounter any issues.

I'll release version 0.9 so that it is available for CocoaPods and Carthage.
