### ISSUE TITLE
Not able to run IOS Example app on iPhone,iphone crashes

### ISSUE THREAD

**Issue by rahulsu** [Building42/Telegraph#47]
I followed all the steps:
Able to run the IOS Example on iPhone simulator, and test https://localhost:9000.
However, when I change the target to IOS device that I have ( my iPhone 6S Plus, with IOS 12.1),
Xcode says my app is running, but the app is crashing as the debug windows of Xcode says.
perhaps, the app is open on iPhone, but it does not respond to any http request as the code had crashed.

Can you please help me to see what I am missing. I am new to IOS dev, intact this is my first app I am playing with...

```
dyld: Library not loaded: @rpath/Telegraph.framework/Telegraph
  Referenced from: /var/containers/Bundle/Application/C43E1AB1-6776-48B2-BDE9-47CA4B827A7C/iOS Example.app/iOS Example
  Reason: image not found
```

**Comment by Zyphrax** [comment]
That's strange, are you using the latest versions of Xcode and Carthage?
- Xcode 10.1 (10B61)
- Carthage 0.31.2

The `dyld: Library not loaded: @rpath/Telegraph.framework/Telegraph` error usually happens if you start the example app and it is unable to find the Telegraph framework.

Perhaps try again by creating a fresh clone:
```
git clone git@github.com:Building42/Telegraph.git
```

Then go into the Telegraph folder and let Carthage install the frameworks:
```
carthage bootstrap
```

After that open Telegraph.xcworkspace.
Select the iOS Example scheme and hit the play button.

**Comment by rahulsu** [comment]
Thank you so much.
You pointed me to go in the right direction to fix this - library issue.
I did not copied the framework libraries and added input paths at Build settings, as were mentioned in the readme.
Followed all the steps in the readme, the issue is resolved.

**Comment by Zyphrax** [comment]
Yeah Carthage sometimes is a bit of a pain, but CocoaPods is causing so many issues with Xcode 10 that I've decided to use Carthage for now. It also results in a cleaner library.

Glad you got it working!
