### ISSUE TITLE
how to set 'Location' header in the response to achieve http-redirection

### ISSUE THREAD

**Issue by rahulsu** [Building42/Telegraph#48]
I wanted this server (IOSExample) to redirect the calling user agent to get redirected. So while sending the response, I would like to insert 'headers' (2nd argument) with `Location : "www.google.com"`. I am not able to find the correct way of coding it.

I tried the below any but `response.headers.location = "www.google.com";`  code is crashing with SIGABRT.

Can you please throw some light on what I am doing wrong ?

Thank you

**Telegraphdemo.swift**
```swift
extension TelegraphDemo {
  /// Raised when the /redirect enpoint is called
  private func redirectHandle(request: HTTPRequest) -> HTTPResponse {
    let response = HTTPResponse(HTTPStatus(code:302, phrase:"Found"), content: "Hello you got redirected")
    response.headers.location = "www.google.com";
    return response;
  }  
}
```

 I added `location` to...

**HTTPHeaders.swift**

```swift
extension HTTPHeaderName {
  static let location = HTTPHeaderName("Location")
}

extension Dictionary where Key == HTTPHeaderName, Value == String {
  public var location: String? {
    get { return self[.location] }
    set { self[.location] = newValue }
  }
}
```

and those for other headers..

**Comment by Zyphrax** [comment]
You were really close to the solution. Here's an example:

**Route registration**
```swift
server.route(.GET, "redirect", serverHandleRedirect)
```

**Route handler**
```swift
/// Raised when the /redirect endpoint is called
private func serverHandleRedirect(request: HTTPRequest) -> HTTPResponse {
  let response = HTTPResponse(.temporaryRedirect)
  response.headers.location = "https://www.google.com"
  return response
}
```
If you want to redirect to an external site, always use the full url (including http:// or https://).
Otherwise it will be a redirect to a local path (for example /index.html).

To make it a bit easier, I've just pushed a commit that adds a few more commonly used headers.

The shortest notation possible would be:

```swift
server.route(.GET, "redirect") { HTTPResponse(.temporaryRedirect, headers: [.location: "https://www.google.com"]) }
```

For redirection you have a few status codes you can use:
- 301: Moved Permanently
- 302: Found
- 303: See Other
- 307: Temporary Redirect
- 308: Permanent Redirect

For more information on that see: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

**Comment by Zyphrax** [comment]
I've release version 0.22 with the extra headers.
After you update to that version, you no longer need the HTTPHeader extension for `location`.

If you have any questions, feel free to reopen this ticket.
