### ISSUE TITLE
CLI Support?

### ISSUE THREAD

**Issue by ratherDashing** [Building42/Telegraph#6]
I tried building a quick and dirty console application using Telegraph and I couldn't get any of the dependencies working.  Is this a Swift limitation or one with Telegraph?  I was able to make one just fine as a regular .app.

Maybe put a sample CLI application using Telegraph?

I am writing a REST service that requires SSL so I chose this framework and I want to compile it down to a CLI application and not a .app.

Thanks!

**Comment by Zyphrax** [comment]
Unfortunately it seems to be quite difficult to use frameworks in a console application:
https://stackoverflow.com/questions/630911/using-frameworks-in-a-command-line-tool

CocoaPods doesn't support console applications: [see this issue](https://github.com/CocoaPods/CocoaPods/issues/6137)
Carthage doesn't seem to support it either: [see this issue](https://github.com/Carthage/Carthage/issues/287)

Perhaps you could make it work by downloading the HTTPParserC, CocoaAsyncSocket and Telegraph projects and adding those to your project, so that they all become part of the same library.

I'm not really sure how to solve this. If you or anyone else has any ideas, I'd be happy to take pull requests or help look into a solution.

**Comment by Zyphrax** [comment]
Telegraph at the moment is mainly targeted on the mobile devices and desktop apps under macOS. Because of its dependencies I currently see no way currently to make it available for CLI applications.

If you want to run a web server as a CLI or for example under Unix, then you might want to checkout [Vapor](https://vapor.codes/),  [Kitura](https://www.kitura.io/) or roll your own implementation using [Swift-NIO](https://github.com/apple/swift-nio).
