### ISSUE TITLE
Always trust certificates?

### ISSUE THREAD

**Issue by ratherDashing** [Building42/Telegraph#7]
I generated the .ca and .der files following the tutorial you linked to and when I start the application the first request creates a pop-up on the server to trust the certificate.  I have clicked "Allow Always" and I've also added the certificate authority and the certificate to the keystone and set it to "Always Trust" and I still get the pop-up.  This is on Mac OS X.  Anyway to prevent that?  I'm afraid when the server reboots someone won't be around to click that dialog.

**Comment by ratherDashing** [comment]
realized if you "trust always" and don't recompile it should trust always.  I was getting this a lot since my service is a WIP

**Comment by Zyphrax** [comment]
You can add the PKCS#12 (.p12) file to the keychain.
Then double click on the key and change access to _Allow all applications to access this item._

![Keychain - Key Access](https://user-images.githubusercontent.com/966500/27452049-32a5df8a-575f-11e7-8bf8-b34c19707d17.png)

That should take care of the Keychain prompts.

**Comment by MikeyLew** [comment]
Will trusting it on your machine before compiling enable it to work when you distribute it?

**Comment by Zyphrax** [comment]
@MikeyLew Self-signed certificates need to be added to the machines that will run the webserver. Unfortunately it isn't possible to compile this into the app, because that would allow developers to override system certificates.

Malicious apps would for example be able to include a certificate for `google.com` and break into Gmail and your web searches.

If you deploy your app using an installer, you can probably add logic to deploy a root certificate for your own certificate authority. Perhaps [this link](https://derflounder.wordpress.com/2011/03/13/adding-new-trusted-root-certificates-to-system-keychain/) might provide some useful info.

**Comment by MikeyLew** [comment]
Thanks for this, so we can't use Telegraph as a HTTPS server within an App distributed on the App store then? Thanks for clarifying 👍

**Comment by Zyphrax** [comment]
@MikeyLew You are free to use Telegraph as an HTTPS server in App Store apps.

For Mac apps it would probably be best if you add a configuration dialog where the user can select the certificate that is going to be used by the server.

For iOS apps you could create your own Certificate Authority. But it would require installation of the certificates on the devices.

If you control the client app you can also perform manual HTTPS certificate validation. See [this section of the README](https://github.com/Building42/Telegraph#http-client) on how to do that.
