### ISSUE TITLE
Package.swift manifest file missing (preventing use in Xcode)

### ISSUE THREAD

**Issue by little-big-h** [Building42/Telegraph#75]
I just tried adding Telegraph as a package in my iOS app and Xcode complains about a missing Package.swift manifest. Having it added will likely help adoption.

**Comment by yvbeek** [comment]
@little-big-h I hope to be able to look into this next weekend.

It is quite a bit of work because the `CocoaAsyncSocket` and `HTTPParserC` dependencies would also require a Package.swift file to set this up. And then I have to make sure that it all works for the different platforms (iOS, macOS, etc.)

**Comment by yvbeek** [comment]
I've spend some time trying to set up the SPM support. It is difficult to set `CocoaAsyncSocket` up in a way that is compatible with CocoaPods, Carthage and SPM. See my efforts here:
https://github.com/Building42/CocoaAsyncSocket

If there is someone here who is a master of SPM, all help is appreciated!

**Comment by yvbeek** [comment]
@little-big-h The `master` branch should support the Swift Package Manager.
I haven't been able to fully test it yet, but could you try it out for me?

**Comment by yvbeek** [comment]
Version 0.28 is now available with SPM support 🚀
