### ISSUE TITLE
Am new to iOS development, am trying to run http(insecure) server on iOS

### ISSUE THREAD

**Issue by trnchawla** [Building42/Telegraph#80]
Hi,

I tried running the example iOS server. Http requests are running fine on same iPad(means I can do HTTP requests on the same iPad where HTTP server is running) but when I try to do HTTP request from another mac/iPhone/iPad on same network, I get an error on the browser. Do I need to have certificate always? 

am running the server on iPad with version 13.3.1 and am trying to access it from the browser on my mac mini with Catalina OS.

**Comment by yvbeek** [comment]
Hi @trnchawla 

Apple is pushing hard for apps to use HTTPS instead of HTTP. But for local networks you can add the `NSAllowsLocalNetworking` key to your Info.plist.

For more info see: [Telegraph - Usage](https://github.com/Building42/Telegraph#usage) and the [Apple Docs](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking)

The Server in the demo starts in a mode that only allows connections from localhost. If you want the server to allow connections from other devices, be sure to remove the `interface` argument:

```
try! server.start(port: 9000, interface: "localhost")
```
```
try! server.start(port: 9000)
```
