### ISSUE TITLE
Bonjour registration and issuing a certificate for the Bonjour hostname

### ISSUE THREAD

**Issue by TomasHubelbauer** [Building42/Telegraph#9]
Hello, please entertain my noob question, but I was wondering whether there is support planned for the Bonjour registration so that my embedded web server instance can be accessed over a proper hostname (like `http://tomas-hubelbauer.local` which I got with _GCDWebServer_) and not just an IP address.

Additionally, do you think it would be possible to issue an Let's Encrypt SSL certificate for that Bonjour hostname as a domain name (will there be a problem with `local` not being a real TLD?) so that I can have a certificate that is trusted by the browser without uploading a new root certificate?

Thanks for your time taken to answer these questions and also thanks for creating this library.

**Comment by Zyphrax** [comment]
Hi Tomas,

**.local domain certificate**
I don't think that Let's Encrypt (or one of the other root CAs) are allowed to issue certificates for the `.local` domain. A [certbot engineer](https://community.letsencrypt.org/t/can-i-create-a-cert-for-a-private-domain/27264/3) wrote the following:

> Industry rules now completely forbid publicly trusted CAs from issuing certificates for internal names like .local. Sorry!

**Bonjour publishing**
I haven't added Bonjour service publishing to the library yet, I might add it in one of the upcoming releases. I'm trying to keep the library fairly small. I'm using the following helper class in one of my projects:

```swift
class WebNetService: NSObject {
  private let workQueue = DispatchQueue.main
  private var netService: NetService?

  let name: String
  let port: Int

  deinit {
    netService?.stop()
  }

  /// Initializes a new WebNetService instance.
  init(name: String, port: Int = WebNetService.defaultPort) {
    self.name = name
    self.port = port
  }

  /// Starts publishing the service.
  func publish() {
    let serviceName = name
    let servicePort = Int32(port)

    workQueue.async {
      self.netService?.stop()
      self.netService = NetService(domain: WebNetService.domain, type: WebNetService.serviceType, name: serviceName, port: servicePort)
      self.netService!.publish(options: .noAutoRename)
    }
  }

  /// Stops publishing the service.
  func unpublish() {
    workQueue.async {
      self.netService?.stop()
      self.netService = nil
    }
  }
}

extension AtlasNetService {
  static let domain = "local."
  static let serviceType = "_http._tcp."
  static let defaultPort = 8000
}
```

Please note that I'm publishing the service on the main thread, I'm doing that because NetServices should be published on a thread that has a runloop. There are a bit nicer, but more complicated ways to handle that, not worth the trouble in my opinion.

I'm also passing `noAutoRename` because I want my service to be unique and not automatically renamed.

If you want you can dive a bit in the NetService delegate and handle the proper delegate calls. I would be careful not to rely too much on Bonjour. We've had some issues with routers not supporting Bonjour.

**Comment by TomasHubelbauer** [comment]
@Zyphrax Thanks for the example Bonjour code, much appreciated! Also thanks for the info on Bonjour compatibility issue.

About the `.local` hostname, I kind of figured it would be that way, which is a pity for me but I guess there are good reasons for it, so I'll live with it.

Have a nice day!

**Comment by eerimoq** [comment]
NetService is deprecated. Would be awesome with builtin in support in the web server.
